- type: antag
  id: Shadowling
  name: roles-antag-shadowling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-shadowling-description
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 7200 # 2 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 180000 # 50 hours
  guides: [ Shadowlings ]

- type: antag
  id: Thrall
  name: roles-antag-thrall-name
  antagonist: true
  setPreference: false
  objective: roles-antag-thrall-description
